# Generated by Django 5.2.4 on 2025-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0002_developer_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='webgames.category'),
        ),
    ]
