# Generated by Django 5.2.4 on 2025-08-14 18:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0003_remove_game_category_game_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='webgames.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
