# Generated by Django 5.2.4 on 2025-08-20 13:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0004_alter_game_file_alter_game_image_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='ten-bucket-cua-ban', custom_domain=None), upload_to='games/files/'),
        ),
    ]
