# Generated by Django 5.2.4 on 2025-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0006_alter_game_file_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'Momo'), ('ZALOPAY', 'ZaloPay')], default='MOMO', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(default=''),
        ),
    ]
