# Generated by Django 5.2.4 on 2025-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgames', '0007_alter_order_payment_method_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'Momo'), ('VNPAY', 'VNPay')], default='MOMO', max_length=10),
        ),
    ]
